version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build: time_manager
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - time_manager/time-manager.env

  vue:
    build: time_manager_front
    ports:
      - "8080:8080"